#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('cfdi2csv', '0.0.1');
$app->add(new \isaactorresmichel\cfdi2csv\Commands\CompileCommand())
  ->getApplication()
  ->setDefaultCommand('cfdi2csv', 'true')
  ->run();
